# ДЛЯ БОЛЬШИХ ОБЪЕМОВ ДАННЫХ СЧИТАЕМ МЕТРИКИ ДЛЯ ОТРЫВКОВ ТЕКСТОВ А ПОТОМ УСРЕДНЯЕМ МЕТРКИ МЕЖДУ СОХРАНЕННЫМИ ФАЙЛАМИ

In [ ]:
https://medium.com/@nicharuch/collocations-identifying-phrases-that-act-like-individual-words-in-nlp-f58a93a2f84a
    
    https://github.com/nicharuc/Collocations/blob/master/Collocations.ipynb
        
        
https://www.nltk.org/_modules/nltk/tag.html
    
https://www.nltk.org/_modules/nltk/collocations.html
    
https://www.nltk.org/api/nltk.metrics.html

In [1]:
from calculate_colocations import get_pos_filtered_colloc_from_corpus_list, get_colloc_from_corpus_list
import pandas as pd
from tqdm import tqdm

In [2]:
texts_lenta = pd.read_csv("3000.csv")

texts_lenta.iloc[0]['texts_3000']

'Указом президента России Бориса Ельцина внесены изменения в  существующую структуру Федеральной службы безопасности РФ, утвержденную в июле прошлого года. Как говорится в поступившем сегодня сообщении Центра общественных связей ФСБ, в соответствии с Основами (Концепцией) государственной политики Российской Федерации по военномустроительству на период до 2005 года, на базе Департамента по борьбе с терроризмом и Управления конституционной безопасности ФСБ создан Департамент по защите конституционного строя и борьбе с терроризмом. В составе департамента организуются три управления с четко определенной компетенцией. В ФСБ отмечают, что "в современных условиях для российскойгосударственности имеют приоритетное значение вопросы защитыконституционного строя, сохранения целостности страны, борьбыс терроризмом и всеми формами экстремизма, а также разведывательно-подрывной деятельностью спецслужб и организаций иностранных государств". Как подчеркивается в сообщении, "органам безопасности в реше

# FREQ POS FILTER

In [3]:

bigramFreqTable, trigramFreqTable, quadgram_freq, filtered_bi, filtered_tri, bigramPMITable, trigramPMITable, quadragramPMITable, bigramChiTable, trigramChiTable =get_pos_filtered_colloc_from_corpus_list(list(texts_lenta['texts_3000']),"rus")


100%|████████████████████████████████████████████████████████████████████████████████| 898/898 [04:22<00:00,  3.42it/s]


In [4]:
def cean_pos_tags(df, ngramm_name):
    clean_words = []
    for i in tqdm(range(len(df))):
        posed_ngramm = df.iloc[i][ngramm_name]
        clean_ngramm = []
        for w in posed_ngramm:
            word = w.split("_")[0]
            clean_ngramm.append(word)
        clean_ngramm = tuple(clean_ngramm)
        clean_words.append(clean_ngramm)
    
    data = { "ngramm":clean_words,"freq":df['freq']}
    clean_df = pd.DataFrame(data) 
    return clean_df
bigramFreqTable_clean = cean_pos_tags(bigramFreqTable,'bigram')


100%|██████████████████████████████████████████████████████████████████████████| 90970/90970 [00:24<00:00, 3718.93it/s]


In [5]:
trigramFreqTable_clean = cean_pos_tags(trigramFreqTable, "trigram")

100%|████████████████████████████████████████████████████████████████████████| 133875/133875 [00:35<00:00, 3820.39it/s]


In [6]:
quadgram_freq_clean = cean_pos_tags(quadgram_freq, "quadgramF")

100%|████████████████████████████████████████████████████████████████████████| 143420/143420 [00:36<00:00, 3899.36it/s]


In [ ]:
filtered_bi, filtered_tri

In [92]:
filtered_tri.head()

trigram  freq
1958   (средство_NOUN, массовый_ADJ, информация_NOUN)    17
12650   (орган_NOUN, исполнительный_ADJ, власть_NOUN)    13
26012      (министр_NOUN, иностранный_ADJ, дело_NOUN)    12
29251        (бюро_NOUN, кредитный_ADJ, история_NOUN)    10
43114        (бывший_ADJ, министр_NOUN, финансы_NOUN)     8

In [7]:
filtered_bi_clean = cean_pos_tags(filtered_bi, "bigram")

100%|██████████████████████████████████████████████████████████████████████████| 21793/21793 [00:05<00:00, 3874.99it/s]


In [94]:
filtered_bi_clean.head()

freq                ngramm
2629     72  (глава, государство)
2548     65    (настоящий, время)
510      37    (ближайший, время)
21525    36       (русский, язык)
5429     35      (право, человек)

In [8]:
filtered_tri_clean = cean_pos_tags(filtered_tri, "trigram")

100%|██████████████████████████████████████████████████████████████████████████| 17142/17142 [00:04<00:00, 3911.18it/s]


In [99]:
filtered_bi_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21904 entries, 2629 to 36679
Data columns (total 2 columns):
freq      21904 non-null int64
ngramm    21904 non-null object
dtypes: int64(1), object(1)
memory usage: 513.4+ KB


In [96]:
filtered_tri_clean.head()

freq                            ngramm
1958     17  (средство, массовый, информация)
12650    13   (орган, исполнительный, власть)
26012    12      (министр, иностранный, дело)
29251    10        (бюро, кредитный, история)
43114     8        (бывший, министр, финансы)

In [11]:
def check_ngramm(freq_ngramm, smart_ngramm,ngramm_name):
    freq_ngramm_list = []
    for ngrm in list(freq_ngramm['ngramm']):
        ngrm_string = ''
        for word in ngrm:
            ngrm_string += word + ' '
        ngrm_string = ngrm_string.strip()
        freq_ngramm_list.append(ngrm_string)
    for ngrm in list(smart_ngramm[ngramm_name]):
        ngrm_string = ''
        for word in ngrm:
            ngrm_string += word + ' '
        ngrm_string = ngrm_string.strip() 
        if ngrm_string not in freq_ngramm_list:
            print(ngrm_string, "NOT_HERE")
        #else:
            #print(ngrm_string, "FOUND")
check_ngramm(trigramFreqTable_clean, filtered_tri_clean,'ngramm' )

# ВЫВОД: В ЧАСТОТНОЙ ХЕРНЕ СОДЕРЖИТСЯ ВСЕ УМНОЕ И ЕЩЕ МНОГО НЕУМНОГО НО ЗА СЧЕТ НЕУМНОГО НАДО ЕЩЕ СМОТРЕТЬ КАК ОНО ЗАПОЛНЯЕТСЯ НГРАММАМИ

In [97]:
bigramFreqTable_clean.head()

freq           ngramm
205   284        (то, что)
398   251         (о, это)
146   228      (по, слово)
162   211       (один, из)
76    211  (отмечать, что)

In [83]:
bigramFreqTable_clean.head()

freq           ngramm
205   284        (то, что)
398   251         (о, это)
146   228      (по, слово)
162   211       (один, из)
76    211  (отмечать, что)

In [103]:
def get_united_numeric_colloc_base (numeric_calc_collocations_list):#все кроме фильтрованных по частям речи
    
    overall_colloc_json = {'2':{},'3':{},'4':{}}
    for colloc in numeric_calc_collocations_list:
        colloc_len = len(colloc)
        for key in list(colloc.keys()):
            if 'gram' in key:
                ngramm_name = key
            else:
                freq_name = key
        n_of_words = str(len(colloc.iloc[0][ngramm_name]))
        print(n_of_words)
        for index in tqdm(range(int(colloc_len))):
            collocation_element = colloc.iloc[index][ngramm_name]
            str_el = ''
            for el in collocation_element:
                str_el += el + ' '
            str_el = str_el.strip()
            overall_colloc_json[n_of_words][str_el] = int(colloc.iloc[index][freq_name])
            """
            if str_el in overall_colloc_json[n_of_words]:
                overall_colloc_json[n_of_words][str_el] *= int(colloc.iloc[index][freq_name])
            else:
                overall_colloc_json[n_of_words][str_el] = int(colloc.iloc[index][freq_name])
            """
            #print(str_el)
        #print("========")
    return overall_colloc_json
#ngramms_list = [bigramFreqTable_clean, trigramFreqTable_clean, quadgram_freq_clean, bigramPMITable, trigramPMITable, quadragramPMITable]
ngramms_list = [bigramFreqTable_clean, trigramFreqTable_clean, quadgram_freq_clean]

raw_colloc_dict = get_united_numeric_colloc_base(ngramms_list)

2


100%|██████████████████████████████████████████████████████████████████████████| 91240/91240 [00:45<00:00, 1992.61it/s]


3


100%|████████████████████████████████████████████████████████████████████████| 133933/133933 [01:12<00:00, 1839.45it/s]


4


100%|████████████████████████████████████████████████████████████████████████| 143433/143433 [01:13<00:00, 1953.24it/s]


In [ ]:
filtered_ngramms_list = [filtered_bi_clean, filtered_tri_clean]

filtered_colloc_dict = get_united_numeric_colloc_base(filtered_ngramms_list)

In [ ]:
filtered_bi, filtered_tri

In [27]:
import json

In [104]:
with open("3000_words_raw_colloc_dict.json", "w") as f:
    json.dump(raw_colloc_dict,f, indent = 4, ensure_ascii = False)

UnicodeEncodeError: 'charmap' codec can't encode character '\u2212' in position 1: character maps to <undefined>

In [32]:
from gensim.models.keyedvectors import FastTextKeyedVectors

C:\Users\Asus\Anaconda3\lib\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [33]:
fasttext = FastTextKeyedVectors.load("D:/fasttext_word2vec/araneum_none_fasttextcbow_300_5_2018/araneum_none_fasttextcbow_300_5_2018.model")

In [63]:
import numpy as np

In [72]:
w2v_colloc_dict = {'2':[],'3':[],'4':[]}
for ngr in colloc_dict.keys():
    for ngramm in colloc_dict[ngr].keys():
        words_list = ngramm.split()
        w2v_list = []
        for word in words_list:
            print(word)
            try:
                w2v = fasttext[word]
                w2v_list.append(w2v)
            except:
                pass
        colleted_w2v_count = len(w2v_list)
        if colleted_w2v_count > 0:
            w2v_colloc_dict[ngr].append(ngramm)
        """
        if colleted_w2v_count > 0:
            vect_sum = 300 * [0]
            for w2v in w2v_list:
                vect_sum += w2v
            vect_sum /=  colleted_w2v_count
        else:
            vect_sum = None
        if np.any(vect_sum):
            w2v_colloc_dict[ngr][ngramm] = vect_sum.reshape(1,-1).tolist()
        #print(words_list, len(w2v_list))
        #break
        """

то
что
о
это
по
слово
один
из
отмечать
что
в
тот
при
это
что
в
заявлять
что
по
он
риа
новость
а
также
он
слово
в
этот
о
то
кроме
то
не
мочь
считать
что
в
россия
в
частность
по
мнение
владимир
путин
в
свой
как
сообщать
сообщать
риа
президент
россия
закон
о
что
он
не
быть
должен
быть
это
сообщать
в
настоящий
не
только
тот
число
подчеркивать
что
сообщать
что
напоминать
что
в
ход
по
данные
тот
же
то
чтобы
в
течение
глава
государство
связывать
с
и
в
год
в
в
страна
в
интервью
находиться
в
в
который
в
первый
настоящий
время
в
результат
в
москва
мочь
быть
потому
что
говорить
о
в
то
связь
с
информация
о
в
ближайший
в
среда
так
как
в
он
и
не
вместе
с
в
рамка
в
качество
участие
в
россия
владимир
то
как
приводить
к
у
мы
который
быть
говорить
в
на
этот
но
и
во
время
в
связь
это
быть
и
другой
пока
не
вопрос
о
в
конец
на
заседание
это
он
это
не
на
то
я
не
он
не
российский
федерация
со
сторона
тот
кто
из
они
быть
принимать
в
случай
с
то
в
четверг
работать
в
между
то
что
они
что
это
в
последний
такой
о

встреча
из
свой
что
хотеть
принимать
на
сша
и
за
он
издание
в
не
считать
правительство
не
не
так
в
армия
что
многие
два
раз
система
не
новый
система
быть
убивать
не
находить
к
ответственность


KeyboardInterrupt: 

In [51]:
from sklearn.metrics.pairwise import cosine_similarity

In [74]:
def get_mean_vector(word2vec_model, words):
    # remove out-of-vocabulary words
    words = [word for word in words if word in word2vec_model.vocab]
    if len(words) >= 1:
        return np.mean(word2vec_model[words], axis=0)
    else:
        return []
average_vector = get_mean_vector(fasttext,['президент','россия'])

In [75]:
w1 = fasttext['президент']
w2 = fasttext['россия']
av = (w1 + w2)/2

In [78]:
av  == average_vector

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [76]:
average_vector

array([ 5.84656596e-02,  9.07742530e-02,  1.23604015e-02,  5.29455394e-02,
        4.68077790e-03,  6.48987517e-02,  8.50475580e-02, -6.80638701e-02,
        8.23792070e-03, -2.92081828e-03, -8.46892297e-02, -9.64557156e-02,
       -1.78939998e-02,  3.38220783e-03, -6.94833845e-02,  1.99300088e-02,
        4.06855345e-03,  6.26083314e-02, -2.79289000e-02, -5.71491197e-02,
        5.35319597e-02, -8.84045362e-02,  1.26196332e-02,  2.35215165e-02,
        4.45453152e-02,  2.13725250e-02,  6.68301582e-02, -4.55579013e-02,
       -1.97311416e-02,  1.27788177e-02, -9.69953239e-02,  4.33633476e-02,
        4.11644541e-02, -6.32641017e-02,  6.54024929e-02,  9.75718573e-02,
       -2.29900014e-02,  8.66349190e-02, -6.00345619e-02, -3.72004695e-03,
        9.21763182e-02,  9.95910447e-03, -1.19028986e-02, -7.08583603e-03,
       -7.67230019e-02, -9.43183377e-02, -6.38427138e-02, -1.81951281e-02,
       -1.38704553e-02,  7.55812973e-02, -2.01514140e-02, -1.07021350e-02,
        6.48044199e-02,  

In [58]:
cosine_similarity( w2v_colloc_dict['4']['президент россия владимир путин'], fasttext['россия'].reshape(1,-1))

array([[0.67623475]])

In [34]:
fasttext['мама']

array([ 0.02138138,  0.01521608,  0.00986125,  0.02197128,  0.06427927,
       -0.05983834, -0.01036269,  0.11541053,  0.03949647,  0.1092683 ,
       -0.03268374,  0.07753018, -0.01910948, -0.01419521, -0.03510416,
       -0.00682221, -0.04483933,  0.02470068, -0.09457379,  0.04353607,
       -0.05531164, -0.0661241 ,  0.08448623, -0.03727661, -0.0334726 ,
       -0.0091603 , -0.019973  , -0.08635031,  0.06308096, -0.01417614,
        0.02844894,  0.07066223,  0.03661515, -0.02241797,  0.00413776,
        0.02788121,  0.00193861, -0.03643694,  0.00609269,  0.00339793,
       -0.10118162, -0.06926611, -0.02972721,  0.06692997,  0.02539542,
       -0.01415602,  0.05340702,  0.00175135, -0.03582824,  0.01966216,
        0.0118806 ,  0.09134583,  0.01786702, -0.03293948,  0.03018913,
        0.04765303, -0.03240753,  0.03975621,  0.07407223, -0.10373922,
       -0.01794396,  0.01649946, -0.01978012,  0.0038766 , -0.02459781,
       -0.04664146, -0.01794693,  0.0562874 ,  0.00174485,  0.03

In [67]:
with open("3000_words_articles_w2v.json", "w") as f:
    json.dump(w2v_colloc_dict,f, indent = 4, ensure_ascii = False)

In [68]:
with open ("3000_words_articles_w2v.json" , "r") as f:
    colloc_db = json.load(f)


In [24]:
import operator
x = {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}
sorted_x_pmi = sorted(colloc_dict['4'].items(), key=lambda kv: kv[1], reverse = True)
sorted_x_pmi

[('президент россия владимир путин', 1061.4517187781873),
 ('как сообщать риа новость', 519.4261185729172),
 ('до сей пора не', 406.4039376144397),
 ('это сообщать риа новость', 328.75483648889576),
 ('риа новость с ссылка', 284.40783774849695),
 ('новость с ссылка на', 241.3808077913619),
 ('сообщать риа новость с', 235.00547265620617),
 ('президент белоруссия александр лукашенко', 204.57640779382513),
 ('сообщать риа новость по', 192.55837505502052),
 ('президент рф владимир путин', 183.03623685096318),
 ('возбуждать уголовный дело по', 158.15553439276803),
 ('министр финансы алексей кудрин', 155.98692491502925),
 ('приходить к вывод что', 155.82002358359256),
 ('информационный агентство риа новость', 149.7955882793863),
 ('президент сша джордж буш', 143.86691339438084),
 ('передавать агентство риа новость', 143.74165558002272),
 ('принимать в первый чтение', 140.657548286279),
 ('что речь идти о', 138.43828024144753),
 ('россия владимир путин называть', 134.80788655902862),
 ('минис

In [ ]:
bigramFreqTable.info()

In [ ]:
trigramPMITable.iloc[0]

In [ ]:
for key in list(trigramPMITable.keys()):
    if 'gram' in key:
        print(key)

In [ ]:
trigramPMITable.head(50)

In [ ]:
clean_words = []
for i in tqdm(range(len(filtered_tri))):
    posed_ngramm = filtered_tri.iloc[i]['trigram']
    clean_ngramm = []
    for w in posed_ngramm:
        word = w.split("_")[0]
        clean_ngramm.append(word)
    clean_ngramm = tuple(clean_ngramm)
    clean_words.append(clean_ngramm)

In [ ]:
trigramChiTable.to_csv("trigramChiTable.csv")

In [ ]:
#data = { "trigram":clean_words,"freq":filtered_tri['freq']}
#filtered_tri_clean = pd.DataFrame(data) 
filtered_tri_clean.head()

In [ ]:
#data = { "filtered_bi":clean_words,"freq":filtered_bi['freq']}
#filtered_bi_clean = pd.DataFrame(data) 
filtered_bi_clean.head()

In [ ]:
#data = { "trigram":clean_words,"freq":quadgram_freq['freq']}
#quadgram_freq_clean = pd.DataFrame(data) 
quadgram_freq_clean.head()

In [ ]:
#data = { "trigram":clean_words,"freq":trigramFreqTable['freq']}
#trigramFreqTable_clean = pd.DataFrame(data) 
trigramFreqTable_clean.head()

In [ ]:
#data = { "bigram":clean_words,"freq":bigramFreqTable['freq']}
#bigramFreqTable_clean = pd.DataFrame(data) 
bigramFreqTable_clean.head()

In [ ]:
stopwords = set(nltk.corpus.stopwords.words('english'))
model_en = Model('english-partut-ud-2.0-170801.udpipe')
texts_en = pd.read_csv("eng_texts.csv")
texts_list = list(texts_en['page_text'])
bigramFreqTable, trigramFreqTable, quadgram_freq, filtered_bi, filtered_tri, bigramPMITable, trigramPMITable, quadragramPMITable, bigramChiTable, trigramChiTable =get_pos_filtered_colloc_from_corpus_list(texts_list, stopwords, model_en)


In [ ]:
quadragramPMITable

# FREQ PMI ETC

In [ ]:
texts_lenta = pd.read_csv("3000.csv")
corpus_list = list(texts_lenta['texts_3000'])
bigramFreqTable, trigramFreqTable,quadgram_freq,  bigramPMITable, trigramPMITable, quadragramPMITable, bigramChiTable, trigramChiTable = get_colloc_from_corpus_list(corpus_list, "rus")


In [ ]:
bigramChiTable

In [ ]:
texts_en = pd.read_csv("eng_texts.csv")
texts_list_en = list(texts_en['page_text'])
bigramFreqTable, trigramFreqTable,quadgram_freq,  bigramPMITable, trigramPMITable, quadragramPMITable , bigramChiTable, trigramChiTable= get_colloc_from_corpus_list(texts_list_en, "en")



In [ ]:
quadragramPMITable